apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: recovery-test

secretGenerator:
  - name: postgres
    envs:
      - postgres-secret.env

generatorOptions:
  disableNameSuffixHash: true
